name: Build Android APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # เปิดให้กดสั่ง Build มือเองได้บนหน้าเว็บ GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # ดึงโค้ด OpenVPN Submodule มาให้ครบ

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Setup Android SDK, NDK & CMake
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '25.1.8937393'
        cmake-version: '3.22.1'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # บังคับใช้ NDK เวอร์ชัน 25 ตรงๆ ตอนสั่งบิวด์เพื่อไม่ให้ระบบหลุดไปใช้เวอร์ชัน 30
      env:
        ANDROID_NDK_ROOT: ${{ 本.android-actions/setup-android.outputs.ndk-path }}
      run: ./gradlew assembleDebug -Pandroid.ndkVersion=25.1.8937393
